### ISSUE TITLE
Can't create an Account in Waterfox!

### ISSUE THREAD

**Issue by LancerEvoVII** [prathameshgaikwad/Innings#19]
**Describe the bug**
I end up at a 404: NOT_FOUND Page after trying to Create An Account..

**To Reproduce**
Use Waterfox, Enter the Website and press on Create an Account.

![CricketError](https://github.com/user-attachments/assets/d8df5386-0548-4d2b-ab2e-d2ee280a178a)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Waterfox
 - Version G6.0.15

**Comment by prathameshgaikwad** [comment]
Hey @LancerEvoVII, this is because this project is not properly deployed for production scenarios. However, you can try it locally.
