### ISSUE TITLE
Signing up with Google doesn't Work

### ISSUE THREAD

**Issue by LancerEvoVII** [prathameshgaikwad/Innings#20]
**Describe the bug**
Can't sign up with Google.

**To Reproduce**
1. Open Waterfox
2. Press on Continue with Google

**Screenshots**
![image](https://github.com/user-attachments/assets/17577f81-c9ad-4541-8225-da37a7594217)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Waterfox
 - Version G6.0.15

**Comment by prathameshgaikwad** [comment]
This app's deployment is not configured for production scenarios. While integrating OAuth2 from Google, there's an option that caters that functionality to select email addresses. I have only included mine.
