### ISSUE TITLE
Innings

### ISSUE THREAD

**Issue by MohitNITTIN** [prathameshgaikwad/Innings#4]
I tired to run the innings project , but found various issue ....... Is your project is completed or Im facing the issue

**Comment by prathameshgaikwad** [comment]
To run the project, navigate into client folder, do npm install

and then navigate to the server folder, do npm install,

Environment variables are required for both the client & the server. Check out the .env.example files in the respective folders.

Also, redis is required for proper functioning of the server. I work on windows, so I use it out of Docker.

**Comment by MohitNITTIN** [comment]
> To run the project, navigate into client folder, do npm install
> 
> and then navigate to the server folder, do npm install,
> 
> Environment variables are required for both the client & the server. Check out the .env.example files in the respective folders.
> 
> Also, redis is required for proper functioning of the server. I work on windows, so I use it out of Docker.
> 
> Finally, start the client and the server.

yess .... I project has been initiated .... but after  creating a tournament .. their is problem with creating team ..... Wait let me send you the error

**Comment by prathameshgaikwad** [comment]
The app is under development. You can create tournaments at the moment, but managing your tournament matches are not properly working yet.

**Comment by MohitNITTIN** [comment]
ohh okay bro ..... by the nice architecture and code
